version: 0.9.8.{build}
skip_tags: true
configuration: Release
platform: x86
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
artifacts:
- path: PoGo.NecroBot.CLI\bin\x86\Release
  name: NecroBot
deploy:
- provider: GitHub
  tag: v$(appveyor_build_version)
  release: NecroBot v$(appveyor_build_version)
  auth_token:
    secure: 6PJ3cwd4I0DRJPv7w8iFAP6iPp94a4omr0Ajl0exmZ3qEnGLdqDwihlgFBFNBHWU
  artifact: NecroBot